apiVersion: apps/v1
kind: Deployment
metadata: 
  name: logs-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: logs
  template: 
    metadata: 
      labels: 
        app: logs
    spec: 
      containers: 
        - name: logs
          # image: us.gcr.io/ticketing-dev-316608/logs
          image: tanay1111/logs
